### ISSUE TITLE
碰到个异常: requestFeature() must be called before adding content

### ISSUE THREAD

**Issue by tzrgaga** [wanggaowan/PhotoPreview#1]
这是我调用部分的代码，我是在 Fragment 里面发起调用
`PhotoPreview.with(this)
                    .sources(imageUrls)
                    .indicatorType(IndicatorType.TEXT)
//                    .fullScreen(true)
                    .defaultShowPosition(currentPosition)
                    .imageLoader((position, source, imageView) -> {
                        GlideApp.with(imageView)
                                .load(((String) source))
                                .into(imageView);
                    })
                    .build()
                    .show();`

` android.util.AndroidRuntimeException: requestFeature() must be called before adding content
        at com.android.internal.policy.PhoneWindow.requestFeature(PhoneWindow.java:444)
        at com.wgw.photo.preview.PreviewDialogFragment.onActivityCreated(PreviewDialogFragment.java:129)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2996)
        at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:580)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:285)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1971)
        at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:305)
        at androidx.fragment.app.DialogFragment.showNow(DialogFragment.java:297)
        at com.wgw.photo.preview.PreviewDialogFragment.showInner(PreviewDialogFragment.java:344)
        at com.wgw.photo.preview.PreviewDialogFragment.show(PreviewDialogFragment.java:301)
        at com.wgw.photo.preview.PhotoPreview.show(PhotoPreview.java:327)
        at com.wgw.photo.preview.PhotoPreview.show(PhotoPreview.java:309)
        at com.xintu.xx.app.show.ui.fragment.TrendsFragment.lambda$onViewCreated$1$TrendsFragment(TrendsFragment.java:100)
        at com.xintu.xx.app.show.ui.fragment.-$$Lambda$TrendsFragment$vNdzk2kQRWx21UWhnushs5YOHck.onImagePreviewClick(Unknown Source:2)
        at com.xx.xx.app.show.ui.adapter.PostListAdapter.lambda$convert$0$PostListAdapter(PostListAdapter.java:59)
        at com.xx.xx.app.show.ui.adapter.-$$Lambda$PostListAdapter$0CFjQaBiX2guKoQV9IMp2yiyVnk.onClick(Unknown Source:4)
        at android.view.View.performClick(View.java:7192)
        at android.view.View.performClickInternal(View.java:7166)
        at android.view.View.access$3500(View.java:824)
        at android.view.View$PerformClick.run(View.java:27592)
        at android.os.Handler.handleCallback(Handler.java:888)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8178)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)`

**Comment by wanggaowan** [comment]
升级到2.4.2，已修复此问题
